# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/faculta/an2 sem 2/AF/MIPS_pipeline/Pipeline/Pipeline.cache/wt} [current_project]
set_property parent.project_path {E:/faculta/an2 sem 2/AF/MIPS_pipeline/Pipeline/Pipeline.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/faculta/an2 sem 2/AF/MIPS_pipeline/Pipeline/Pipeline.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/faculta/an2 sem 2/AF/MIPS_pipeline_material/mips16/MEM.vhd}
  {E:/faculta/an2 sem 2/AF/MIPS_pipeline_material/mips16/MPG.vhd}
  {E:/faculta/an2 sem 2/AF/MIPS_pipeline_material/mips16/ExecutionUnit.vhd}
  {E:/faculta/an2 sem 2/AF/MIPS_pipeline_material/mips16/IDecode.vhd}
  {E:/faculta/an2 sem 2/AF/MIPS_pipeline_material/mips16/IFetch.vhd}
  {E:/faculta/an2 sem 2/AF/MIPS_pipeline_material/mips16/MainControl.vhd}
  {E:/faculta/an2 sem 2/AF/MIPS_pipeline_material/mips16/SSD.vhd}
  {E:/faculta/an2 sem 2/AF/MIPS_pipeline_material/mips16/lab7_4.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/faculta/an2 sem 2/AF/test_env2/test_env.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{E:/faculta/an2 sem 2/AF/test_env2/test_env.srcs/constrs_1/new/constraints.xdc}}]


synth_design -top lab7_4 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab7_4.dcp

catch { report_utilization -file lab7_4_utilization_synth.rpt -pb lab7_4_utilization_synth.pb }
